/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.ManagerUser;

import GUI.AddSales.*;
import GUI.AddSales.addSalesFrame.*;
import DB.dbConnection;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.time.Instant;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.Vector;
import model.userModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.swing.JRViewer;
import org.apache.log4j.Logger;

/**
 *
 * @author kulas
 */
public class attendance_report extends javax.swing.JDialog {

    /**
     * Creates new form serachProductFormGRN
     */
    static Logger log1 = Logger.getLogger(attendance_report.class.getName());

    private userModel um;
    DefaultTableModel userTableModel;

    public attendance_report(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        um = new userModel();
        userTableModel = (DefaultTableModel) attendanceTable.getModel();
        searchModel();
        fromDate.setDate(Date.from(Instant.now()));
        toDate.setDate(Date.from(Instant.now()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        attendanceTable = new javax.swing.JTable();
        selectItemBtn = new javax.swing.JButton();
        fromDate = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        toDate = new com.toedter.calendar.JDateChooser();
        employeeCombo = new javax.swing.JComboBox();
        statusCombo = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("A T T E N D A N C E   D E T A I L S");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 22)); // NOI18N
        jLabel1.setText("Attendance Details");

        attendanceTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "On Time", "Off Time", "Status", "Employee"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        attendanceTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                attendanceTableKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(attendanceTable);
        if (attendanceTable.getColumnModel().getColumnCount() > 0) {
            attendanceTable.getColumnModel().getColumn(0).setMinWidth(100);
            attendanceTable.getColumnModel().getColumn(0).setPreferredWidth(100);
            attendanceTable.getColumnModel().getColumn(0).setMaxWidth(100);
            attendanceTable.getColumnModel().getColumn(1).setMinWidth(80);
            attendanceTable.getColumnModel().getColumn(1).setPreferredWidth(80);
            attendanceTable.getColumnModel().getColumn(1).setMaxWidth(80);
            attendanceTable.getColumnModel().getColumn(2).setMinWidth(80);
            attendanceTable.getColumnModel().getColumn(2).setPreferredWidth(80);
            attendanceTable.getColumnModel().getColumn(2).setMaxWidth(80);
            attendanceTable.getColumnModel().getColumn(3).setMinWidth(75);
            attendanceTable.getColumnModel().getColumn(3).setPreferredWidth(75);
            attendanceTable.getColumnModel().getColumn(3).setMaxWidth(75);
        }

        selectItemBtn.setBackground(new java.awt.Color(0, 51, 51));
        selectItemBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        selectItemBtn.setForeground(new java.awt.Color(255, 255, 255));
        selectItemBtn.setText("Search");
        selectItemBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153), null, new java.awt.Color(153, 153, 153)));
        selectItemBtn.setContentAreaFilled(false);
        selectItemBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        selectItemBtn.setOpaque(true);
        selectItemBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectItemBtnActionPerformed(evt);
            }
        });

        fromDate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fromDateMouseClicked(evt);
            }
        });

        jLabel2.setText("From");

        jLabel3.setText("To");

        employeeCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-- All Employee --", "Admin", "Manager", "Cashier 1", "Cashier 2" }));
        employeeCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                employeeComboItemStateChanged(evt);
            }
        });
        employeeCombo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                employeeComboMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                employeeComboMousePressed(evt);
            }
        });

        statusCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--- Select Here ---", "Present", "Absent" }));
        statusCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                statusComboItemStateChanged(evt);
            }
        });
        statusCombo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                statusComboMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                statusComboMouseReleased(evt);
            }
        });

        jLabel4.setText("Filtering Employee Position");

        jLabel5.setText("Filtering Attendance status");

        jButton1.setBackground(new java.awt.Color(0, 51, 51));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Report");
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 51, 51));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Search Date Range");
        jButton2.setContentAreaFilled(false);
        jButton2.setOpaque(true);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("jButton3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 782, Short.MAX_VALUE)
                            .addComponent(selectItemBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(employeeCombo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(fromDate, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel2))
                                            .addGap(36, 36, 36)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(toDate, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel3))))
                                    .addComponent(jLabel4))
                                .addGap(83, 83, 83)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(statusCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton2))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(86, 86, 86))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addGap(3, 3, 3)
                        .addComponent(fromDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(16, 16, 16)
                        .addComponent(jButton2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(3, 3, 3)
                        .addComponent(toDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(employeeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statusCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(selectItemBtn)
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void selectItemBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectItemBtnActionPerformed
        int employe = employeeCombo.getSelectedIndex();
        int staus = statusCombo.getSelectedIndex();

        if (employe == 0) {
            um.loadallEployeeAttenndance(employe, staus, userTableModel);
        } else if (employe == 1) {
            um.loadallManagerAttenndance(employe, staus, userTableModel);
        } else if (employe == 2) {
            um.loadallManagerAttenndance(employe, staus, userTableModel);
        } else if (employe == 3) {
            um.loadallManagerAttenndance(employe, staus, userTableModel);
        } else if (employe == 4) {
            um.loadallManagerAttenndance(employe, staus, userTableModel);
        }

    }//GEN-LAST:event_selectItemBtnActionPerformed

    private void attendanceTableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_attendanceTableKeyPressed
        try {
            DefaultTableModel dtm = (DefaultTableModel) attendanceTable.getModel();
            addSalesFrame.pBarcode.setText(dtm.getValueAt(attendanceTable.getSelectedRow(), 0).toString());
            addSalesFrame.name.setText(dtm.getValueAt(attendanceTable.getSelectedRow(), 1).toString());
            addSalesFrame.qty.setText(dtm.getValueAt(attendanceTable.getSelectedRow(), 2).toString());
            addSalesFrame.price.setText(dtm.getValueAt(attendanceTable.getSelectedRow(), 3).toString());

            this.dispose();
        } catch (Exception e) {
            e.printStackTrace();
            log1.debug(e.getMessage());
        }
    }//GEN-LAST:event_attendanceTableKeyPressed

    private void fromDateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fromDateMouseClicked

//        int employe = employeeCombo.getSelectedIndex();
//        int staus = statusCombo.getSelectedIndex();
//
//        //communicate with class
//        um.loadAttendanceTable(employe, staus, userTableModel);

    }//GEN-LAST:event_fromDateMouseClicked

    private void employeeComboMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employeeComboMouseClicked
//         int employe = employeeCombo.getSelectedIndex();
//        int staus = statusCombo.getSelectedIndex();
//
//        //communicate with class
//        um.loadAttendanceTable(employe, staus, userTableModel);
    }//GEN-LAST:event_employeeComboMouseClicked

    private void statusComboMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_statusComboMouseClicked
//        int employe = employeeCombo.getSelectedIndex();
//        int staus = statusCombo.getSelectedIndex();
//
//        //communicate with class
//        um.loadAttendanceTable(employe, staus, userTableModel);
    }//GEN-LAST:event_statusComboMouseClicked

    private void statusComboMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_statusComboMouseReleased
//        int employe = employeeCombo.getSelectedIndex();
//        int staus = statusCombo.getSelectedIndex();
//
//        //communicate with class
//        um.loadAttendanceTable(employe, staus, userTableModel);
    }//GEN-LAST:event_statusComboMouseReleased

    private void employeeComboMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employeeComboMousePressed
//        int employe = employeeCombo.getSelectedIndex();
//        int staus = statusCombo.getSelectedIndex();
//
//        //communicate with class
//        um.loadAttendanceTable(employe, staus, userTableModel);
    }//GEN-LAST:event_employeeComboMousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String reportPath = "C:\\Users\\kulas\\JaspersoftWorkspace\\MyReports\\staf_atten.jrxml";
        //parameter
        Map m = new HashMap();
        //  m.put("Date", new Date(System.currentTimeMillis()));
        //datesource
        // JREmptyDataSource datasource = new JREmptyDataSource();

        try {

            JasperReport jc = JasperCompileManager.compileReport(reportPath);

            JasperPrint jp = JasperFillManager.fillReport(jc, m, DB.dbConnection.getConnection());
            JRViewer jv = new JRViewer(jp);
            GUI.AddSales.report gu = new GUI.AddSales.report();
            gu.tabbedPane.add(jv);
            System.out.println("ok");
            gu.setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void employeeComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_employeeComboItemStateChanged
// int employe = employeeCombo.getSelectedIndex();
//        int staus = statusCombo.getSelectedIndex();
//
//        //communicate with class
//        um.loadAttendanceTable(employe, staus, userTableModel);        


    }//GEN-LAST:event_employeeComboItemStateChanged

    private void statusComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_statusComboItemStateChanged
//        int employe = employeeCombo.getSelectedIndex();
//        int staus = statusCombo.getSelectedIndex();
//
//        //communicate with class
//        um.loadAttendanceTable(employe, staus, userTableModel);
    }//GEN-LAST:event_statusComboItemStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Date d1 = fromDate.getDate();
        Date d2 = toDate.getDate();

        um.daterange(d1, d2, userTableModel);


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        String reportPath = "C:\\Users\\kulas\\JaspersoftWorkspace\\MyReports\\staf_atten.jrxml";
        //parameter
        Map m = new HashMap();
      //  m.put("Date", new Date(System.currentTimeMillis()));

        try {

            JasperReport jc = JasperCompileManager.compileReport(reportPath);

            JasperPrint jp = JasperFillManager.fillReport(jc, m, DB.dbConnection.getConnection());
            JRViewer jv = new JRViewer(jp);
            this.dispose();
            GUI.AddSales.report gu = new GUI.AddSales.report();
            gu.tabbedPane.add(jv);
            //  System.out.println("ok");
            gu.setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
        }


    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(attendance_report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(attendance_report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(attendance_report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(attendance_report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                attendance_report dialog = new attendance_report(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable attendanceTable;
    private javax.swing.JComboBox employeeCombo;
    private com.toedter.calendar.JDateChooser fromDate;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton selectItemBtn;
    private javax.swing.JComboBox statusCombo;
    private com.toedter.calendar.JDateChooser toDate;
    // End of variables declaration//GEN-END:variables

    public void searchModel() {
        try {
            DefaultTableModel dtm = (DefaultTableModel) attendanceTable.getModel();
            dtm.setRowCount(0);

            ResultSet rs = DB.dbConnection.getConnection().createStatement().executeQuery("SELECT * FROM reporting_to_work");
            while (rs.next()) {
                Vector v = new Vector();
//                v.add(rs.getString("id"));
                v.add(rs.getString("date"));
                v.add(rs.getString("on_time"));
                v.add(rs.getString("off_time"));
                v.add(rs.getString("status"));
                v.add(rs.getString("staff_id_staff"));
                dtm.addRow(v);
            }
        } catch (Exception e) {
            e.printStackTrace();
            log1.debug(e.getMessage());
        }
    }

}
