/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.ManagerUser;

import GUI.*;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import model.userModel;
import org.apache.log4j.Logger;

/**
 *
 * @author kulas
 */
public class managerUserFrame extends javax.swing.JFrame {

    /**
     * Creates new form dashBoardFrame
     */
    static Logger log1 = Logger.getLogger(managerUserFrame.class.getName());
    
     Connection conn;
    PreparedStatement pst;
    
    private userModel um;
    DefaultTableModel userTableModel;

    public managerUserFrame() {
        initComponents();
        conn = DB.dbConnection.getConnection();
        um = new userModel();
        id.setEditable(false);
        userTableModel = (DefaultTableModel) userTable.getModel();
        setBackground(new Color(0, 0, 0, 0));
        jPanel3.setEnabled(false);
        jPanel3.setVisible(false);
        setting3.setEnabled(false);
        setting3.setVisible(false);
        userTableLoad();
        showDate();
        showTime();
    }

    void showDate() {
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("yyyy-MM-dd");
        Date.setText(s.format(d));
    }

    void showTime() {
        new Timer(0, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                Date d = new Date();
                SimpleDateFormat s = new SimpleDateFormat("hh:mm:ss");
                Time.setText(s.format(d));
            }
        }
        ).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        viewsetting = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        log = new javax.swing.JLabel();
        data = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        setting = new javax.swing.JLabel();
        setting3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        home = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        customer = new javax.swing.JLabel();
        staff = new javax.swing.JLabel();
        item = new javax.swing.JLabel();
        suppliers = new javax.swing.JLabel();
        dashboard = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        userManager = new javax.swing.JLabel();
        addSales = new javax.swing.JLabel();
        user = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Date = new javax.swing.JLabel();
        Time = new javax.swing.JLabel();
        dashBoardMain = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        combo = new javax.swing.JComboBox();
        un = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        userTable = new javax.swing.JTable();
        updateBtn = new javax.swing.JButton();
        removeBtn = new javax.swing.JButton();
        companyAddBtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        pw1 = new javax.swing.JPasswordField();
        id = new javax.swing.JTextField();
        attendence_inn = new javax.swing.JButton();
        Salary_calculation = new javax.swing.JButton();
        attendence_off1 = new javax.swing.JButton();
        attendence_report = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setMaximumSize(new java.awt.Dimension(450, 675));
        jPanel1.setMinimumSize(new java.awt.Dimension(450, 675));
        jPanel1.setPreferredSize(new java.awt.Dimension(450, 675));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setLayout(null);

        viewsetting.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        viewsetting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/settings.JPG"))); // NOI18N
        viewsetting.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewsettingMouseClicked(evt);
            }
        });
        jPanel3.add(viewsetting);
        viewsetting.setBounds(0, 0, 157, 141);

        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        jPanel3.add(exit);
        exit.setBounds(0, 100, 160, 40);

        log.setText("jLabel1");
        log.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logMouseClicked(evt);
            }
        });
        jPanel3.add(log);
        log.setBounds(0, 0, 160, 50);

        data.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.add(data);
        data.setBounds(0, 50, 160, 40);

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 431, 160, 140));

        jPanel2.setMaximumSize(new java.awt.Dimension(450, 675));
        jPanel2.setMinimumSize(new java.awt.Dimension(450, 675));
        jPanel2.setPreferredSize(new java.awt.Dimension(450, 675));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        setting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/mechanical-gears-.png"))); // NOI18N
        setting.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setting.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                settingMouseClicked(evt);
            }
        });
        jPanel2.add(setting, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 570, -1, -1));

        setting3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/mechanical-gears-.png"))); // NOI18N
        setting3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setting3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                setting3MouseClicked(evt);
            }
        });
        jPanel2.add(setting3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 570, -1, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CEYLON LAKSHA");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        home.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        home.setForeground(new java.awt.Color(255, 255, 255));
        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/home.png"))); // NOI18N
        home.setText("   Home");
        home.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        home.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
        });
        jPanel2.add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 190, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/vertical-line.png"))); // NOI18N
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 150, -1, -1));

        customer.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        customer.setForeground(new java.awt.Color(255, 255, 255));
        customer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/customer.png"))); // NOI18N
        customer.setText("   Customer");
        customer.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        customer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        customer.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);
        customer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customerMouseClicked(evt);
            }
        });
        jPanel2.add(customer, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 190, -1));

        staff.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        staff.setForeground(new java.awt.Color(255, 255, 255));
        staff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/employees.png"))); // NOI18N
        staff.setText("   Staff");
        staff.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        staff.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        staff.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);
        staff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                staffMouseClicked(evt);
            }
        });
        jPanel2.add(staff, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 190, -1));

        item.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        item.setForeground(new java.awt.Color(255, 255, 255));
        item.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/box.png"))); // NOI18N
        item.setText("   Item");
        item.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        item.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        item.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);
        item.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemMouseClicked(evt);
            }
        });
        jPanel2.add(item, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 190, -1));

        suppliers.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        suppliers.setForeground(new java.awt.Color(255, 255, 255));
        suppliers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/hotel-supplier.png"))); // NOI18N
        suppliers.setText("   Suppliers");
        suppliers.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        suppliers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        suppliers.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);
        suppliers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                suppliersMouseClicked(evt);
            }
        });
        jPanel2.add(suppliers, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 190, -1));

        dashboard.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        dashboard.setForeground(new java.awt.Color(255, 255, 255));
        dashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/menu (2).png"))); // NOI18N
        dashboard.setText("   Dashboard");
        dashboard.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        dashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dashboard.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);
        dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboardMouseClicked(evt);
            }
        });
        jPanel2.add(dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, 190, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("All right reserved.");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 650, -1, -1));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Concept By Heshan Kulasooriya. ");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 640, -1, -1));

        jLabel9.setBackground(new java.awt.Color(9, 14, 14));
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Copyright @ 2021 REYGREN.");
        jLabel9.setOpaque(true);
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 600, 160, 60));

        userManager.setFont(new java.awt.Font("Calibri", 1, 22)); // NOI18N
        userManager.setForeground(new java.awt.Color(255, 255, 255));
        userManager.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/profile.png"))); // NOI18N
        userManager.setText("   Manage User");
        userManager.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        userManager.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        userManager.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);
        jPanel2.add(userManager, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 190, -1));

        addSales.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        addSales.setForeground(new java.awt.Color(255, 255, 255));
        addSales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/cart (1).png"))); // NOI18N
        addSales.setText("   Add Sales");
        addSales.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        addSales.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addSales.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);
        addSales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addSalesMouseClicked(evt);
            }
        });
        jPanel2.add(addSales, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 190, -1));

        user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/profile.png"))); // NOI18N
        user.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userMouseClicked(evt);
            }
        });
        jPanel2.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 570, -1, -1));
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 680));

        Date.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        Date.setForeground(new java.awt.Color(255, 255, 255));
        Date.setText("Date");
        jPanel2.add(Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        Time.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        Time.setForeground(new java.awt.Color(255, 255, 255));
        Time.setText("Time");
        jPanel2.add(Time, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

        dashBoardMain.setBackground(new java.awt.Color(204, 204, 204));
        dashBoardMain.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/wes dancer~2.png"))); // NOI18N
        dashBoardMain.setOpaque(true);
        jPanel2.add(dashBoardMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 288, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, 288, -1));

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/close-button (2).png"))); // NOI18N
        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });
        jPanel1.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(1131, 11, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Admin");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 50, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Status :");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 50, -1, -1));

        jLabel3.setBackground(new java.awt.Color(0, 51, 51));
        jLabel3.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("   Manage User");
        jLabel3.setOpaque(true);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(341, 41, 790, -1));

        jLabel5.setText("Status");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(341, 150, -1, -1));

        jLabel7.setText("Username");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(341, 191, -1, -1));

        jLabel8.setText("Password");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(341, 229, -1, -1));

        combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Admin", "Manager", "Cashier 1", "Cashier 2" }));
        jPanel1.add(combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(471, 147, 189, -1));

        un.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unActionPerformed(evt);
            }
        });
        jPanel1.add(un, new org.netbeans.lib.awtextra.AbsoluteConstraints(471, 188, 189, -1));

        userTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Status", "Username", "Password"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        userTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(userTable);
        if (userTable.getColumnModel().getColumnCount() > 0) {
            userTable.getColumnModel().getColumn(0).setMinWidth(0);
            userTable.getColumnModel().getColumn(0).setPreferredWidth(0);
            userTable.getColumnModel().getColumn(0).setMaxWidth(0);
            userTable.getColumnModel().getColumn(3).setMinWidth(0);
            userTable.getColumnModel().getColumn(3).setPreferredWidth(0);
            userTable.getColumnModel().getColumn(3).setMaxWidth(0);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(714, 109, 417, 172));

        updateBtn.setBackground(new java.awt.Color(0, 51, 51));
        updateBtn.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        updateBtn.setForeground(new java.awt.Color(255, 255, 255));
        updateBtn.setText("Update");
        updateBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), null, new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204)));
        updateBtn.setContentAreaFilled(false);
        updateBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updateBtn.setOpaque(true);
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });
        jPanel1.add(updateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(927, 303, 86, -1));

        removeBtn.setBackground(new java.awt.Color(0, 51, 51));
        removeBtn.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        removeBtn.setForeground(new java.awt.Color(255, 255, 255));
        removeBtn.setText("Remove");
        removeBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), null, new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204)));
        removeBtn.setContentAreaFilled(false);
        removeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        removeBtn.setOpaque(true);
        removeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBtnActionPerformed(evt);
            }
        });
        jPanel1.add(removeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1045, 303, 86, -1));

        companyAddBtn.setBackground(new java.awt.Color(0, 51, 51));
        companyAddBtn.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        companyAddBtn.setForeground(new java.awt.Color(255, 255, 255));
        companyAddBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/plus (2).png"))); // NOI18N
        companyAddBtn.setText("Add Details");
        companyAddBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), null, new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204)));
        companyAddBtn.setContentAreaFilled(false);
        companyAddBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        companyAddBtn.setOpaque(true);
        companyAddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                companyAddBtnActionPerformed(evt);
            }
        });
        jPanel1.add(companyAddBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(527, 301, 133, 27));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 358, 808, -1));
        jPanel1.add(pw1, new org.netbeans.lib.awtextra.AbsoluteConstraints(471, 226, 189, -1));

        id.setForeground(new java.awt.Color(255, 255, 255));
        id.setBorder(null);
        id.setInheritsPopupMenu(true);
        jPanel1.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 109, 20, -1));

        attendence_inn.setBackground(new java.awt.Color(0, 51, 51));
        attendence_inn.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        attendence_inn.setForeground(new java.awt.Color(255, 255, 255));
        attendence_inn.setText("Mark Attendence");
        attendence_inn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), null, new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204)));
        attendence_inn.setContentAreaFilled(false);
        attendence_inn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        attendence_inn.setOpaque(true);
        attendence_inn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attendence_innActionPerformed(evt);
            }
        });
        jPanel1.add(attendence_inn, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 391, 230, 110));

        Salary_calculation.setBackground(new java.awt.Color(0, 51, 51));
        Salary_calculation.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        Salary_calculation.setForeground(new java.awt.Color(255, 255, 255));
        Salary_calculation.setText("Salary Calculation");
        Salary_calculation.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), null, new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204)));
        Salary_calculation.setContentAreaFilled(false);
        Salary_calculation.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Salary_calculation.setOpaque(true);
        Salary_calculation.setPreferredSize(new java.awt.Dimension(97, 23));
        Salary_calculation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Salary_calculationActionPerformed(evt);
            }
        });
        jPanel1.add(Salary_calculation, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 520, 230, 130));

        attendence_off1.setBackground(new java.awt.Color(0, 51, 51));
        attendence_off1.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        attendence_off1.setForeground(new java.awt.Color(255, 255, 255));
        attendence_off1.setText("Mark Leave Time");
        attendence_off1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), null, new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204)));
        attendence_off1.setContentAreaFilled(false);
        attendence_off1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        attendence_off1.setOpaque(true);
        attendence_off1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attendence_off1ActionPerformed(evt);
            }
        });
        jPanel1.add(attendence_off1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 390, 230, 110));

        attendence_report.setBackground(new java.awt.Color(0, 51, 51));
        attendence_report.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        attendence_report.setForeground(new java.awt.Color(255, 255, 255));
        attendence_report.setText("Attendance Report");
        attendence_report.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), null, new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204)));
        attendence_report.setContentAreaFilled(false);
        attendence_report.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        attendence_report.setOpaque(true);
        attendence_report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attendence_reportActionPerformed(evt);
            }
        });
        jPanel1.add(attendence_report, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 527, 230, 120));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1166, -1));

        setSize(new java.awt.Dimension(1166, 675));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        System.exit(0);
        this.dispose();
    }//GEN-LAST:event_closeMouseClicked

    private void setting3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_setting3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_setting3MouseClicked

    private void settingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingMouseClicked
        jPanel3.setEnabled(true);
        jPanel3.setVisible(true);
        setting.setEnabled(false);
        setting.setVisible(false);
        setting3.setEnabled(true);
        setting3.setVisible(true);
    }//GEN-LAST:event_settingMouseClicked

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        System.exit(0);
        this.dispose();
    }//GEN-LAST:event_exitMouseClicked

    private void logMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logMouseClicked
        new loginForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        for (double i = 0.0; i <= 1.0; i = i + 0.1) {
            String val = i + "";
            float f = Float.valueOf(val);
            this.setOpacity(f);
            try {
                Thread.sleep(50);
            } catch (Exception e) {
log1.debug(e.getMessage());
            }
        }
        jLabel1.requestFocus();
    }//GEN-LAST:event_formWindowOpened

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
        // TODO add your handling code here:
        new GUI.Home.homeFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homeMouseClicked

    private void customerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerMouseClicked
        // TODO add your handling code here:
        new GUI.Customer.customerFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_customerMouseClicked

    private void staffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_staffMouseClicked
        // TODO add your handling code here:
        new GUI.Staff.staffFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_staffMouseClicked

    private void itemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemMouseClicked
        // TODO add your handling code here:
        new GUI.Items.itemsFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_itemMouseClicked

    private void suppliersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_suppliersMouseClicked
        // TODO add your handling code here:
        new GUI.Supplier.supplierFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_suppliersMouseClicked

    private void addSalesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addSalesMouseClicked
        // TODO add your handling code here:
        new GUI.AddSales.addSalesFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_addSalesMouseClicked

    private void dashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardMouseClicked
        // TODO add your handling code here:
        new dashBoardFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_dashboardMouseClicked

    private void viewsettingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewsettingMouseClicked
        // TODO add your handling code here:
        new GUI.Backup_Restore.backup_restoreFrame().setVisible(true);
    }//GEN-LAST:event_viewsettingMouseClicked

    private void unActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        String i = id.getText();
        String u = un.getText();
        if (un.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Please enter Username");
                return;
            }
        String job = combo.getSelectedItem().toString();
        String password2;
        char[] charpassword1 = pw1.getPassword();
        if (pw1.getPassword().equals("")) {
                JOptionPane.showMessageDialog(this, "Please enter Passwaord");
                return;
            }
        String password1 = String.valueOf(charpassword1);

        String result = um.updateUser(i, u, job, password1);
        //um.loadTable("", 0, userTableModel);
        JOptionPane.showConfirmDialog(rootPane, result, "Message !", 0, 1);
        userTableLoad();
        clean();
    }//GEN-LAST:event_updateBtnActionPerformed

    private void removeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBtnActionPerformed
         String query = "DELETE FROM user where user_id = ? ";
        try {
            pst = conn.prepareStatement(query);
            pst.setString(1, id.getText());
            pst.execute();
            
            JOptionPane.showConfirmDialog(null, "Do you want to delete this?","Realy ?",0,1);
            userTableLoad();
            clean();
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, e);
            log1.debug(e.getMessage());
        }
    }//GEN-LAST:event_removeBtnActionPerformed

    private void companyAddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_companyAddBtnActionPerformed
        // TODO add your handling code here:
        String u = un.getText();
        if (un.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Please enter Username");
                return;
            }
        String job = combo.getSelectedItem().toString();
        String password2;
        char[] charpassword1 = pw1.getPassword();
        if (pw1.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Please enter password");
                return;
            }
        String password1 = new String(charpassword1);

        String userInser = um.insertUser(u, job, password1);
        JOptionPane.showConfirmDialog(rootPane, userInser, "Username and Password Added..", 0, 1);
        clean();
        userTableLoad();
    }//GEN-LAST:event_companyAddBtnActionPerformed

    private void userTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userTableMouseClicked
        try {
            DefaultTableModel dtm = (DefaultTableModel) userTable.getModel();
            id.setText(dtm.getValueAt(userTable.getSelectedRow(), 0).toString());
            combo.setSelectedItem(dtm.getValueAt(userTable.getSelectedRow(), 1).toString());
            un.setText(dtm.getValueAt(userTable.getSelectedRow(), 2).toString());
            pw1.setText(dtm.getValueAt(userTable.getSelectedRow(), 3).toString());

        } catch (Exception e) {
            e.printStackTrace();
            log1.debug(e.getMessage());
        }
    }//GEN-LAST:event_userTableMouseClicked

    private void attendence_innActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attendence_innActionPerformed
        this.dispose();
        new attendence_inn(this, true).setVisible(true);
        
    }//GEN-LAST:event_attendence_innActionPerformed

    private void Salary_calculationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Salary_calculationActionPerformed
        new attendance(this, rootPaneCheckingEnabled).setVisible(true);
        

    }//GEN-LAST:event_Salary_calculationActionPerformed

    private void attendence_reportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attendence_reportActionPerformed
        new attendance_report(this, rootPaneCheckingEnabled).setVisible(true);


    }//GEN-LAST:event_attendence_reportActionPerformed

    private void userMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userMouseClicked
        new aboutus(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_userMouseClicked

    private void attendence_off1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attendence_off1ActionPerformed
         this.dispose();
        new attendence_off(this, true).setVisible(true);
    }//GEN-LAST:event_attendence_off1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(managerUserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(managerUserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(managerUserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(managerUserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new managerUserFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Date;
    private javax.swing.JButton Salary_calculation;
    private javax.swing.JLabel Time;
    private javax.swing.JLabel addSales;
    private javax.swing.JButton attendence_inn;
    private javax.swing.JButton attendence_off1;
    private javax.swing.JButton attendence_report;
    private javax.swing.JLabel close;
    private javax.swing.JComboBox combo;
    private javax.swing.JButton companyAddBtn;
    private javax.swing.JLabel customer;
    private javax.swing.JLabel dashBoardMain;
    private javax.swing.JLabel dashboard;
    private javax.swing.JLabel data;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel home;
    private javax.swing.JTextField id;
    private javax.swing.JLabel item;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel log;
    private javax.swing.JPasswordField pw1;
    private javax.swing.JButton removeBtn;
    private javax.swing.JLabel setting;
    private javax.swing.JLabel setting3;
    private javax.swing.JLabel staff;
    private javax.swing.JLabel suppliers;
    private javax.swing.JTextField un;
    private javax.swing.JButton updateBtn;
    private javax.swing.JLabel user;
    private javax.swing.JLabel userManager;
    private javax.swing.JTable userTable;
    private javax.swing.JLabel viewsetting;
    // End of variables declaration//GEN-END:variables

    void clean() {
        id.setText(""); 
        un.setText(""); 
        pw1.setText("");
        combo.setSelectedItem(1);
    }

    private void userTableLoad() {
        try {
            DefaultTableModel dtm = (DefaultTableModel) userTable.getModel();
            dtm.setRowCount(0);
            ResultSet rs = DB.dbConnection.getConnection().createStatement().executeQuery("SELECT * FROM user");
            while (rs.next()) {
                Vector v = new Vector();
                v.add(rs.getString("user_id"));
                v.add(rs.getString("status"));
                v.add(rs.getString("un"));
                v.add(rs.getString("pw"));
                dtm.addRow(v);
            }
        } catch (Exception e) {
            e.printStackTrace();
            log1.debug(e.getMessage());
        }

    }
}
