/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Supplier;

import GUI.*;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import model.userModel;
import GUI.Supplier.updateSupplier;
import org.apache.log4j.Logger;

/**
 *
 * @author kulas
 */
public class supplierFrame_manager extends javax.swing.JFrame {

    /**
     * Creates new form dashBoardFrame
     */
    static Logger log1 = Logger.getLogger(supplierFrame_manager.class.getName());
    
    private userModel um;
    DefaultTableModel useTableModel;

    public supplierFrame_manager() {
        initComponents();
        autoId();
        id.setEditable(false);
        um = new userModel();
        useTableModel = (DefaultTableModel) companyTable.getModel();
        setBackground(new Color(0, 0, 0, 0));
        jPanel3.setEnabled(false);
        jPanel3.setVisible(false);
        setting3.setEnabled(false);
        setting3.setVisible(false);
        showDate();
        showTime();
        companyTableLoad();
        suppliersTableLoad();
    }

    void showDate() {
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("yyyy-MM-dd");
        Date.setText(s.format(d));
    }

    void showTime() {
        new Timer(0, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                Date d = new Date();
                SimpleDateFormat s = new SimpleDateFormat("hh:mm:ss");
                Time.setText(s.format(d));
            }
        }
        ).start();
    }

    void clean() {
        autoId();
        companyName.setText("");
        addressTextArea.setText("");
    }

    private void autoId() {
        try {
            ResultSet rs = DB.dbConnection.getConnection().createStatement().executeQuery("SELECT id_company FROM company ORDER BY id_company DESC LIMIT 1");
            if (rs.next()) {
                String rnno = rs.getString("id_company");
                int co = rnno.length();
                String txt = rnno.substring(0, 2);
                String num = rnno.substring(2, co);
                int n = Integer.parseInt(num);
                n++;
                String snum = Integer.toString(n);
                String ftxt = txt + snum;
                id.setText(ftxt);

            } else {
                id.setText("1111");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
            log1.debug(e.getMessage());
        }

    }

    void companyTableLoad() {
        try {
            DefaultTableModel dtm = (DefaultTableModel) companyTable.getModel();
            dtm.setRowCount(0);
            ResultSet rs = DB.dbConnection.getConnection().createStatement().executeQuery("SELECT * FROM company");
            while (rs.next()) {
                Vector v = new Vector();
                v.add(rs.getString("id_company"));
                v.add(rs.getString("name"));
                v.add(rs.getString("address"));
                dtm.addRow(v);
            }
        } catch (Exception e) {
            e.printStackTrace();
            log1.debug(e.getMessage());
        }
    }

    public static void suppliersTableLoad() {
        try {
            DefaultTableModel dtm = (DefaultTableModel) supplierTable.getModel();
            dtm.setRowCount(0);
            ResultSet rs = DB.dbConnection.getConnection().createStatement().executeQuery("SELECT * FROM suppliers");
            while (rs.next()) {
                Vector v = new Vector();
                v.add(rs.getString("mobile"));
                v.add(rs.getString("name"));
                v.add(rs.getString("company_id_company"));
                v.add(rs.getString("email"));
                dtm.addRow(v);
            }
        } catch (Exception e) {
            e.printStackTrace();
            log1.debug(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        viewsetting = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        log = new javax.swing.JLabel();
        data = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        setting = new javax.swing.JLabel();
        setting3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        home = new javax.swing.JLabel();
        customer = new javax.swing.JLabel();
        staff = new javax.swing.JLabel();
        item = new javax.swing.JLabel();
        suppliers = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        dashboard = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        userManager = new javax.swing.JLabel();
        addSales = new javax.swing.JLabel();
        user = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Date = new javax.swing.JLabel();
        Time = new javax.swing.JLabel();
        dashBoardMain = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        companyName = new javax.swing.JTextField();
        removeBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        addressTextArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        companyTable = new javax.swing.JTable();
        companyAddBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        supplierTable = new javax.swing.JTable();
        uSupplier = new javax.swing.JButton();
        remove = new javax.swing.JButton();
        newSupplier = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setMaximumSize(new java.awt.Dimension(1170, 685));
        jPanel1.setMinimumSize(new java.awt.Dimension(1170, 685));
        jPanel1.setPreferredSize(new java.awt.Dimension(1170, 685));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Manager");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 50, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Status :");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 50, -1, -1));

        jPanel3.setLayout(null);

        viewsetting.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        viewsetting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/settings.JPG"))); // NOI18N
        viewsetting.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewsettingMouseClicked(evt);
            }
        });
        jPanel3.add(viewsetting);
        viewsetting.setBounds(0, 0, 157, 141);

        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        jPanel3.add(exit);
        exit.setBounds(0, 100, 160, 40);

        log.setText("jLabel1");
        log.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logMouseClicked(evt);
            }
        });
        jPanel3.add(log);
        log.setBounds(0, 0, 160, 50);

        data.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        data.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dataMouseClicked(evt);
            }
        });
        jPanel3.add(data);
        data.setBounds(0, 50, 160, 40);

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 431, 160, 140));

        jPanel2.setMaximumSize(new java.awt.Dimension(450, 675));
        jPanel2.setMinimumSize(new java.awt.Dimension(450, 675));
        jPanel2.setPreferredSize(new java.awt.Dimension(450, 675));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        setting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/mechanical-gears-.png"))); // NOI18N
        setting.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setting.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                settingMouseClicked(evt);
            }
        });
        jPanel2.add(setting, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 570, -1, -1));

        setting3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/mechanical-gears-.png"))); // NOI18N
        setting3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setting3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                setting3MouseClicked(evt);
            }
        });
        jPanel2.add(setting3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 570, -1, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CEYLON LAKSHA");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        home.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        home.setForeground(new java.awt.Color(255, 255, 255));
        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/home.png"))); // NOI18N
        home.setText("   Home");
        home.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        home.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
        });
        jPanel2.add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 190, -1));

        customer.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        customer.setForeground(new java.awt.Color(255, 255, 255));
        customer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/customer.png"))); // NOI18N
        customer.setText("   Customer");
        customer.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        customer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        customer.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);
        customer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customerMouseClicked(evt);
            }
        });
        jPanel2.add(customer, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 190, -1));

        staff.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        staff.setForeground(new java.awt.Color(255, 255, 255));
        staff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/employees.png"))); // NOI18N
        staff.setText("   Staff");
        staff.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        staff.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        staff.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);
        staff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                staffMouseClicked(evt);
            }
        });
        jPanel2.add(staff, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 190, -1));

        item.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        item.setForeground(new java.awt.Color(255, 255, 255));
        item.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/box.png"))); // NOI18N
        item.setText("   Item");
        item.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        item.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        item.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);
        item.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemMouseClicked(evt);
            }
        });
        jPanel2.add(item, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 190, -1));

        suppliers.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        suppliers.setForeground(new java.awt.Color(255, 255, 255));
        suppliers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/hotel-supplier.png"))); // NOI18N
        suppliers.setText("   Suppliers");
        suppliers.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        suppliers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        suppliers.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);
        jPanel2.add(suppliers, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 190, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/vertical-line.png"))); // NOI18N
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 350, -1, -1));

        dashboard.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        dashboard.setForeground(new java.awt.Color(255, 255, 255));
        dashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/menu (2).png"))); // NOI18N
        dashboard.setText("   Dashboard");
        dashboard.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        dashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dashboard.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);
        dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboardMouseClicked(evt);
            }
        });
        jPanel2.add(dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, 190, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("All right reserved.");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 650, -1, -1));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Concept By Heshan Kulasooriya. ");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 640, -1, -1));

        jLabel9.setBackground(new java.awt.Color(9, 14, 14));
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Copyright @ 2021 REYGREN.");
        jLabel9.setOpaque(true);
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 600, 160, 60));

        userManager.setFont(new java.awt.Font("Calibri", 1, 22)); // NOI18N
        userManager.setForeground(new java.awt.Color(255, 255, 255));
        userManager.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/profile.png"))); // NOI18N
        userManager.setText("   Manage User");
        userManager.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        userManager.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        userManager.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);
        userManager.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userManagerMouseClicked(evt);
            }
        });
        jPanel2.add(userManager, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 190, -1));

        addSales.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        addSales.setForeground(new java.awt.Color(255, 255, 255));
        addSales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/cart (1).png"))); // NOI18N
        addSales.setText("   Add Sales");
        addSales.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        addSales.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addSales.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);
        addSales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addSalesMouseClicked(evt);
            }
        });
        jPanel2.add(addSales, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 190, -1));

        user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/profile.png"))); // NOI18N
        user.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userMouseClicked(evt);
            }
        });
        jPanel2.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 570, -1, -1));

        jLabel1.setMaximumSize(new java.awt.Dimension(450, 675));
        jLabel1.setMinimumSize(new java.awt.Dimension(450, 675));
        jLabel1.setPreferredSize(new java.awt.Dimension(450, 675));
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -5, 910, 1010));

        Date.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        Date.setForeground(new java.awt.Color(255, 255, 255));
        Date.setText("Date");
        jPanel2.add(Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        Time.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        Time.setForeground(new java.awt.Color(255, 255, 255));
        Time.setText("Time");
        jPanel2.add(Time, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

        dashBoardMain.setBackground(new java.awt.Color(204, 204, 204));
        dashBoardMain.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/wes dancer~2.png"))); // NOI18N
        dashBoardMain.setOpaque(true);
        jPanel2.add(dashBoardMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 288, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, 288, -1));

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/close-button (2).png"))); // NOI18N
        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });
        jPanel1.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(1133, 11, -1, -1));

        jLabel6.setBackground(new java.awt.Color(0, 51, 51));
        jLabel6.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("   Supplier Handling Area");
        jLabel6.setIconTextGap(10);
        jLabel6.setOpaque(true);
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(341, 41, 792, -1));

        jPanel5.setBackground(new java.awt.Color(226, 220, 220));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Company", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 14))); // NOI18N

        jLabel5.setText("Company Name");

        jLabel8.setText("Address ");

        companyName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                companyNameActionPerformed(evt);
            }
        });

        removeBtn.setBackground(new java.awt.Color(0, 51, 51));
        removeBtn.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        removeBtn.setForeground(new java.awt.Color(255, 255, 255));
        removeBtn.setText("Remove");
        removeBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), null, new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204)));
        removeBtn.setContentAreaFilled(false);
        removeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        removeBtn.setOpaque(true);
        removeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBtnActionPerformed(evt);
            }
        });

        jLabel3.setText("If you want to add new Compay, Please use following Space to add your  ");

        jLabel12.setText("records.");

        addressTextArea.setColumns(20);
        addressTextArea.setRows(5);
        jScrollPane1.setViewportView(addressTextArea);

        companyTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Address"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        companyTable.setPreferredSize(new java.awt.Dimension(200, 64));
        companyTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                companyTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(companyTable);
        if (companyTable.getColumnModel().getColumnCount() > 0) {
            companyTable.getColumnModel().getColumn(0).setMinWidth(50);
            companyTable.getColumnModel().getColumn(0).setPreferredWidth(50);
            companyTable.getColumnModel().getColumn(0).setMaxWidth(50);
            companyTable.getColumnModel().getColumn(1).setMinWidth(130);
            companyTable.getColumnModel().getColumn(1).setPreferredWidth(130);
            companyTable.getColumnModel().getColumn(1).setMaxWidth(130);
        }

        companyAddBtn.setBackground(new java.awt.Color(0, 51, 51));
        companyAddBtn.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        companyAddBtn.setForeground(new java.awt.Color(255, 255, 255));
        companyAddBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/plus (2).png"))); // NOI18N
        companyAddBtn.setText("Add Details");
        companyAddBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), null, new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204)));
        companyAddBtn.setContentAreaFilled(false);
        companyAddBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        companyAddBtn.setOpaque(true);
        companyAddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                companyAddBtnActionPerformed(evt);
            }
        });

        updateBtn.setBackground(new java.awt.Color(0, 51, 51));
        updateBtn.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        updateBtn.setForeground(new java.awt.Color(255, 255, 255));
        updateBtn.setText("Update");
        updateBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), null, new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204)));
        updateBtn.setContentAreaFilled(false);
        updateBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updateBtn.setOpaque(true);
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        jLabel14.setText("ID");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel14)
                                .addGap(106, 106, 106))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel5))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(companyName)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)))
                                    .addComponent(id, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(companyAddBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, Short.MAX_VALUE)))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(removeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(companyName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(0, 56, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(removeBtn)
                    .addComponent(updateBtn)
                    .addComponent(companyAddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(341, 115, -1, -1));

        jPanel4.setBackground(new java.awt.Color(226, 220, 220));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Supplier Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 14))); // NOI18N

        jLabel11.setText("This is Supplier Area.You can see all details of suppliers, The essential details of the suppliers involved in your business are listed below. ");

        jLabel13.setText("If you need to add or update of suppliers, Please Click following Buttons.");

        supplierTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mobile", "Name", "Company", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(supplierTable);
        if (supplierTable.getColumnModel().getColumnCount() > 0) {
            supplierTable.getColumnModel().getColumn(0).setMinWidth(100);
            supplierTable.getColumnModel().getColumn(0).setPreferredWidth(100);
            supplierTable.getColumnModel().getColumn(0).setMaxWidth(100);
        }

        uSupplier.setBackground(new java.awt.Color(0, 51, 51));
        uSupplier.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        uSupplier.setForeground(new java.awt.Color(255, 255, 255));
        uSupplier.setText("Update");
        uSupplier.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), null, new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204)));
        uSupplier.setContentAreaFilled(false);
        uSupplier.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        uSupplier.setOpaque(true);
        uSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uSupplierActionPerformed(evt);
            }
        });

        remove.setBackground(new java.awt.Color(0, 51, 51));
        remove.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        remove.setForeground(new java.awt.Color(255, 255, 255));
        remove.setText("Remove");
        remove.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), null, new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204)));
        remove.setContentAreaFilled(false);
        remove.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        remove.setOpaque(true);
        remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeActionPerformed(evt);
            }
        });

        newSupplier.setBackground(new java.awt.Color(0, 51, 51));
        newSupplier.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        newSupplier.setForeground(new java.awt.Color(255, 255, 255));
        newSupplier.setText("New Supplier");
        newSupplier.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), null, new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204)));
        newSupplier.setContentAreaFilled(false);
        newSupplier.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        newSupplier.setOpaque(true);
        newSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newSupplierActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13)
                    .addComponent(jScrollPane3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(uSupplier, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(remove, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newSupplier, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(newSupplier)
                        .addGap(18, 18, 18)
                        .addComponent(uSupplier)
                        .addGap(18, 18, 18)
                        .addComponent(remove))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(341, 397, 792, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 680));

        setSize(new java.awt.Dimension(1170, 682));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        System.exit(0);
        this.dispose();
    }//GEN-LAST:event_closeMouseClicked

    private void setting3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_setting3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_setting3MouseClicked

    private void settingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingMouseClicked
        jPanel3.setEnabled(true);
        jPanel3.setVisible(true);
        setting.setEnabled(false);
        setting.setVisible(false);
        setting3.setEnabled(true);
        setting3.setVisible(true);
    }//GEN-LAST:event_settingMouseClicked

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        System.exit(0);
        this.dispose();
    }//GEN-LAST:event_exitMouseClicked

    private void logMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logMouseClicked
        new loginForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        for (double i = 0.0; i <= 1.0; i = i + 0.1) {
            String val = i + "";
            float f = Float.valueOf(val);
            this.setOpacity(f);
            try {
                Thread.sleep(50);
            } catch (Exception e) {
log1.debug(e.getMessage());
            }
        }
        jLabel1.requestFocus();
    }//GEN-LAST:event_formWindowOpened

    private void dashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardMouseClicked
        // TODO add your handling code here:
        new dashBoardFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_dashboardMouseClicked

    private void addSalesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addSalesMouseClicked
        // TODO add your handling code here:
        new GUI.AddSales.addSalesFrame_manager().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_addSalesMouseClicked

    private void itemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemMouseClicked
        // TODO add your handling code here:
        new GUI.Items.itemsFrame_manager().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_itemMouseClicked

    private void staffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_staffMouseClicked
        // TODO add your handling code here:
        new GUI.Staff.staffFrame_manager().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_staffMouseClicked

    private void customerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerMouseClicked
        // TODO add your handling code here:
        new GUI.Customer.customerFrame_manager().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_customerMouseClicked

    private void userManagerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userManagerMouseClicked
        // TODO add your handling code here:
          JOptionPane.showMessageDialog(rootPane, "Sorry! You can't Enter..","Warnning", 1, null);
    }//GEN-LAST:event_userManagerMouseClicked

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
        // TODO add your handling code here:
        new GUI.Home.homeFrame_manager().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homeMouseClicked

    private void viewsettingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewsettingMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_viewsettingMouseClicked

    private void companyNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_companyNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_companyNameActionPerformed

    private void removeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBtnActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_removeBtnActionPerformed

    private void companyAddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_companyAddBtnActionPerformed
        // TODO add your handling code here:
        String i = id.getText();
        String name = companyName.getText();
        if (companyName.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please enter Name of Company");
            return;
        }
        String address = addressTextArea.getText();
        if (addressTextArea.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please enter Address of Company");
            return;
        }

        String resrultStaff = um.insertCompany(i, name, address);

        JOptionPane.showConfirmDialog(rootPane, resrultStaff, "Company Adding..", 0, 1);
        clean();
        companyTableLoad();
    }//GEN-LAST:event_companyAddBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        String n = companyName.getText();
        if (companyName.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please enter Name of Company");
            return;
        }
        String address = addressTextArea.getText();
         if (addressTextArea.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please enter Address of Company");
            return;
        }
        String i = id.getText();

        String result = um.updateCompany(n, address, i);
        um.loadTable("", 0, useTableModel);
        JOptionPane.showConfirmDialog(rootPane, result, "Message !", 0, 1);
        clean();

    }//GEN-LAST:event_updateBtnActionPerformed

    private void uSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uSupplierActionPerformed
        // TODO add your handling code here:
        new updateSupplier(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_uSupplierActionPerformed

    private void removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_removeActionPerformed

    private void newSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newSupplierActionPerformed
        // TODO add your handling code here:
        new addSupplier(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_newSupplierActionPerformed

    private void companyTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_companyTableMouseClicked
        try {
            DefaultTableModel dtm = (DefaultTableModel) companyTable.getModel();
            id.setText(dtm.getValueAt(companyTable.getSelectedRow(), 0).toString());
            companyName.setText(dtm.getValueAt(companyTable.getSelectedRow(), 1).toString());
            addressTextArea.setText(dtm.getValueAt(companyTable.getSelectedRow(), 2).toString());

        } catch (Exception e) {
            e.printStackTrace();
            log1.debug(e.getMessage());
        }
    }//GEN-LAST:event_companyTableMouseClicked

    private void dataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataMouseClicked
        new GUI.Backup_Restore.backup_restoreFrame_manager().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_dataMouseClicked

    private void userMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userMouseClicked
        new aboutus(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_userMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(supplierFrame_manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(supplierFrame_manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(supplierFrame_manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(supplierFrame_manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new supplierFrame_manager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Date;
    private javax.swing.JLabel Time;
    private javax.swing.JLabel addSales;
    private javax.swing.JTextArea addressTextArea;
    private javax.swing.JLabel close;
    private javax.swing.JButton companyAddBtn;
    private javax.swing.JTextField companyName;
    private javax.swing.JTable companyTable;
    private javax.swing.JLabel customer;
    private javax.swing.JLabel dashBoardMain;
    private javax.swing.JLabel dashboard;
    private javax.swing.JLabel data;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel home;
    private javax.swing.JTextField id;
    private javax.swing.JLabel item;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel log;
    private javax.swing.JButton newSupplier;
    private javax.swing.JButton remove;
    private javax.swing.JButton removeBtn;
    private javax.swing.JLabel setting;
    private javax.swing.JLabel setting3;
    private javax.swing.JLabel staff;
    public static javax.swing.JTable supplierTable;
    private javax.swing.JLabel suppliers;
    private javax.swing.JButton uSupplier;
    private javax.swing.JButton updateBtn;
    private javax.swing.JLabel user;
    private javax.swing.JLabel userManager;
    private javax.swing.JLabel viewsetting;
    // End of variables declaration//GEN-END:variables

    public static void updatetableLoad() {
        DefaultTableModel dtm = (DefaultTableModel) supplierTable.getModel();
        updateSupplier.mobile.setText(dtm.getValueAt(supplierTable.getSelectedRow(), 0).toString());
        updateSupplier.name.setText(dtm.getValueAt(supplierTable.getSelectedRow(), 1).toString());
        //updateSupplier.c.setText(dtm.getValueAt(supplierTable.getSelectedRow(), 2).toString());
           updateSupplier.combo.setSelectedItem(dtm.getValueAt(supplierTable.getSelectedRow(), 2).toString());
        updateSupplier.email.setText(dtm.getValueAt(supplierTable.getSelectedRow(), 3).toString());
    }
}
