/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Items;

import DB.dbConnection;
import static GUI.Items.addProducts.qty1;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.util.Vector;
import org.apache.log4j.Logger;

/**
 *
 * @author kulas
 */
public class serachProductFormGRN extends javax.swing.JDialog {

    /**
     * Creates new form serachProductFormGRN
     */
    static Logger log1 = Logger.getLogger(serachProductFormGRN.class.getName());
    
    public serachProductFormGRN(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        searchModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        searchProducts = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        searchTable = new javax.swing.JTable();
        selectItemBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 22)); // NOI18N
        jLabel1.setText("Search Products Details");

        searchProducts.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                searchProductsKeyTyped(evt);
            }
        });

        searchTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Item Name", "Buying Price", "QTY", "Total"
            }
        ));
        jScrollPane1.setViewportView(searchTable);
        if (searchTable.getColumnModel().getColumnCount() > 0) {
            searchTable.getColumnModel().getColumn(0).setMinWidth(80);
            searchTable.getColumnModel().getColumn(0).setPreferredWidth(80);
            searchTable.getColumnModel().getColumn(0).setMaxWidth(80);
            searchTable.getColumnModel().getColumn(1).setMinWidth(400);
            searchTable.getColumnModel().getColumn(1).setPreferredWidth(400);
            searchTable.getColumnModel().getColumn(1).setMaxWidth(400);
        }

        selectItemBtn.setBackground(new java.awt.Color(0, 51, 51));
        selectItemBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        selectItemBtn.setForeground(new java.awt.Color(255, 255, 255));
        selectItemBtn.setText("Select Item");
        selectItemBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153), null, new java.awt.Color(153, 153, 153)));
        selectItemBtn.setContentAreaFilled(false);
        selectItemBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        selectItemBtn.setOpaque(true);
        selectItemBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectItemBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchProducts)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 782, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(selectItemBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(searchProducts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(selectItemBtn)
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void searchProductsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchProductsKeyTyped
        // TODO add your handling code here:
       searchModel();
    }//GEN-LAST:event_searchProductsKeyTyped

    private void selectItemBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectItemBtnActionPerformed
        try {
            DefaultTableModel dtm = (DefaultTableModel) searchTable.getModel();
            addProducts.searchProducts.setText(dtm.getValueAt(searchTable.getSelectedRow(), 0).toString());
            addProducts.name.setText(dtm.getValueAt(searchTable.getSelectedRow(), 1).toString());
            addProducts.bp.setText(dtm.getValueAt(searchTable.getSelectedRow(),2).toString());
            addProducts.qty.setText(dtm.getValueAt(searchTable.getSelectedRow(),3).toString());
            qty1.setText("1");
            this.dispose();
        } catch (Exception e) {
            e.printStackTrace();
            log1.debug(e.getMessage());
        }
    }//GEN-LAST:event_selectItemBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(serachProductFormGRN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(serachProductFormGRN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(serachProductFormGRN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(serachProductFormGRN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                serachProductFormGRN dialog = new serachProductFormGRN(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField searchProducts;
    private javax.swing.JTable searchTable;
    private javax.swing.JButton selectItemBtn;
    // End of variables declaration//GEN-END:variables

    private void searchModel() {
         try {
            DefaultTableModel dtm = (DefaultTableModel) searchTable.getModel();
            dtm.setRowCount(0);
            
            ResultSet rs = DB.dbConnection.getConnection().createStatement().executeQuery("SELECT * FROM grn WHERE item LIKE '%" + searchProducts.getText() + "%'");
            while (rs.next()) {                
                Vector v= new Vector();
                v.add(rs.getString("id_grn"));
                v.add(rs.getString("item"));
                v.add(rs.getString("qty_price"));
                v.add(rs.getString("qty"));
                v.add(rs.getString("total"));
                dtm.addRow(v);
            }
        } catch (Exception e) {
            e.printStackTrace();
            log1.debug(e.getMessage());
        } }
}
